### ISSUE TITLE
How can i custom the radius, font  of chip ???

### ISSUE THREAD

**Issue by duckm8795** [hootsuite/nachos#10]
I want to custom Chip like the below image .But i can't find any function to do it.
![zxa](https://cloud.githubusercontent.com/assets/20036318/23337998/995285e6-fc31-11e6-9284-60f8be1a6ed9.png)

**Comment by simon-tse-hs** [comment]
Oooh Hey @duckm8795 , we don't have that supported right now. We can look into for you. I think we would have to allow for the `ChipSpan` to be created with a desired radius and default to the full circle if invalid or nothing is provided.

**Comment by chnouman** [comment]
@simon-tse-hs  Any update related to this?
