### ISSUE TITLE
chipTextColor not working

### ISSUE THREAD

**Issue by AmineNac** [hootsuite/nachos#36]
I'm trying to change the chip text color by setting it into the xml layout file like so : app:chipTextColor="@color/white" but it's not working.

**Comment by MadhanSekar93** [comment]
Hi,
Faced the same issue. Text color assigned static inside ChipSpan class. 
So that app:chipTextColor=""  not working. I have made changes in ChipSpan class as per my need.

**Comment by simon-tse-hs** [comment]
@MadhanSekar93 do you have a Pull Request for that code change?

**Comment by acmeuno** [comment]
Facing same problem here. Not changing even programatically.
Not sure yet if has something to do with but my NachosTextView is inside a TextInputLayout...

**Comment by AbubakerMustafa** [comment]
Hi !
Faced the same problem.I added it as module in my project and change chip_default_text_color as per requirement.

**Comment by zekedran** [comment]
for me i changed the color to `ffffff` and didn't work, but surprisingly `f0f0f0` works...!

![image](https://user-images.githubusercontent.com/8567893/38765875-839e5930-3fc1-11e8-9030-d56a96db1a26.png)

**Comment by chnouman** [comment]
@zekedran thanks buddy have you get the reason behind this?

**Comment by mokkun** [comment]
The issue only happens with the white color, because 0xFF equals to -1 (signed decimal) and the code is only applying color if `chipTextColor != -1`.
