### ISSUE TITLE
Chips ordering

### ISSUE THREAD

**Issue by btcontract** [hootsuite/nachos#40]
I've noticed that `getChipValues` returns a list containing chips exactly as they were entered when I'm using an emulator but on actual phone (Xiaomi Mi5, MIUI 9) order is sometimes skewed. For example, user may enter `One Two Tree` and the result would be `List(One, Three, Two)`.

Is this a planned behavior? If yes, can it be customized to always preserve an order?

**Comment by D330** [comment]
I think you can use `getText().toString().split(" ")`
