### ISSUE TITLE
Chips' Text color not working.

### ISSUE THREAD

**Issue by chaostools** [hootsuite/nachos#51]
first of all  :

# Thankyou!!! ❤️ ❤️ ❤️ 

I have spend my past 4 hours searching for an edit_text that could make ' tags' while writing and doesn't use a list of data . This `ChipTerminatorHandler.BEHAVIOR_CHIPIFY_TO_TERMINATOR` is freaking amazing!

Secondly i am having a small issue . i tried the following code:
```xml
com.hootsuite.nachos.NachoTextView
        android:id="@+id/nacho_text_view"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:chipSpacing="2dp"
        app:chipBackground="@color/blue"
        app:chipTextColor="#ffffff"
        app:chipTextSize="16dp"
        app:chipHeight="30dp"
        app:chipVerticalSpacing="3dp"/>
``` 
but it is showing chips with bgcolor  as blue but text color as black. what am i doing wrong?

and lastly, naming a chip library which some would call 'tags' , 'hashtags' , 'chips', 'labels', 'flags' or even 'badges' , but "Nachos" ?wicked 🤣

**Comment by bluebery** [comment]
try passing a color resource for `app:chipTextColor`, like `@color/white`?
looks like it expects a resource here `mChipTextColor = attributes.getColor(R.styleable.NachoTextView_chipTextColor, Color.TRANSPARENT);`

if you want to use a hex value, you can set the value programatically using 

```
    public void setChipTextColor(@ColorInt int chipTextColor) {
        mChipTextColor = chipTextColor;
        invalidateChips();
    }
```

on `NachoTextView`
