### ISSUE TITLE
custom chip textcolor not working

### ISSUE THREAD

**Issue by omkar243** [hootsuite/nachos#54]
` app:chipTextColor="@color/white"`

also tried programmatically 

`nachosTexView.setTextColor();`

**Comment by dudhatparesh** [comment]
Same here.

**Comment by davidcrotty** [comment]
Interesting, it seems that any resource pointing to pure white works, but if you try any other colour its fine. So a workaround could be using FFFFFE for example. Not a fix by any stretch

**Comment by RyoMMX** [comment]
@davidcrotty  thanks man this worked for me.

> Same issue for me. It seems that any resource pointing to pure white work does not work (using `app:chipTextColor`), but if you try any other colour its fine. So a workaround could be using FFFFFE for example. Not a fix by any stretch

**Comment by pratikvar** [comment]
Yes, I encounter the same issue where only white color (FFFFFF) is not getting honored by lib for app:chipTextColor as well as  nachosTexView.setTextColor()

**Comment by omkar243** [comment]
> Same issue for me. It seems that any resource pointing to pure white work does not work (using `app:chipTextColor`), but if you try any other colour its fine. So a workaround could be using FFFFFE for example. Not a fix by any stretch
