### ISSUE TITLE
setText not working on Nougat

### ISSUE THREAD

**Issue by neil-power-hs** [hootsuite/nachos#6]
Using setText to create a NachoTextView with chips works on API 23 and below as expected
![device-2016-11-09-102519](https://cloud.githubusercontent.com/assets/14058331/20149990/728e7920-a668-11e6-9b4b-0bb82f4d4bdc.png)

However, on API 24 and above (Nougat), the chips are show as ellipses as shown below.
![device-2016-11-09-102222](https://cloud.githubusercontent.com/assets/14058331/20150020/8e066bea-a668-11e6-9533-8478f9756fcb.png)

Tapping on either NachoTextView causes the chips to be rendered as normal.
![device-2016-11-09-102254](https://cloud.githubusercontent.com/assets/14058331/20150027/9b1dc864-a668-11e6-9a4f-dbcfc70b5911.png)

**Comment by byronsliger** [comment]
I have the same problem, NachoTextView only refresh the chips when I've shown or hidden the keyboard.
Please help.

**Comment by simon-tse-hs** [comment]
@byronsliger  yes we are well aware of it as @neil-power-hs and I identified it during our testing with Nougat. Our progress on a solution only saw that we hacked a solution and had to do with how different Nougat draws text views. 
Our current solution was to request focus of the field, but that is far from ideal. Give that a try first.

**Comment by byronsliger** [comment]
@simon-tse-hs I saw that, but if you have shown the keyboard and to request focus of the field, the problem persists.

**Comment by BrunoCarrier** [comment]
@simon-tse-hs This library looks really promising, but that issue is a deal breaker to me.  I couldn't figure a way to fix this behaviour cleanly

**Comment by neil-power-hs** [comment]
@BrunoCarrier, @sherry-yuan-hs has a fix in for this issue via https://github.com/hootsuite/nachos/pull/11. We will be creating a 1.1 release soon to pull in the fix and others.

**Comment by sherry-yuan-hs** [comment]
@byronsliger @BrunoCarrier we recently released Nachos 1.1, which includes a fix for this.

**Comment by BrunoCarrier** [comment]
Thanks @sherry-yuan-hs !
