### ISSUE TITLE
Conflict with API 28

### ISSUE THREAD

**Issue by Vivek5287445** [hootsuite/nachos#67]
error: duplicate value for resource 'attr/chipSpacing' with config ''.
Message{kind=ERROR, text=error: duplicate value for resource 'attr/chipSpacing' with config ''., sources=[C:\Users\Vivek Kaushik\.gradle\caches\transforms-1\files-1.1\appcompat-v7-28.0.0-rc01.aar\664fa20d824381dbf468c0902e41e423\res\values\values.xml:1304:5-69], original message=, tool name=Optional.of(AAPT)}

**Comment by simon-tse-hs** [comment]
Thanks Vivek, I guess we'll need to change this for newer versions.

**Comment by LinX64** [comment]
The interesting point is I couldn't find anything related to `attr/chipSpacing` in : 

`appcompat-v7-28.0.0.aar\589e798727821b8116778f2bb8f76780\res\values\values.xml`

Can't wait to see the update from the developer
.

**Comment by JetLiu92** [comment]
@Vivek5287445 Can you provide the appcompat-v7-28.0.0-rc01.aar which causes this exception. I cannot find the version includes 'attr/chipSpacing'. Thank you very much!

**Comment by simon-tse-hs** [comment]
Have a pull request and my peers will look at it. But Can @Vivek5287445 and @LinX64 look to see if it works for you?

**Comment by Vivek5287445** [comment]
It's working now. I am closing this issue.

**Comment by simon-tse-hs** [comment]
@Vivek5287445 how is it working now? What did you do different?

**Comment by LinX64** [comment]
It should work now. However, `28.0.0` will be the latest release (For the support library) and it's better to update to the `AndroidX` dependencies from now on.

**Comment by guitorioadar** [comment]
error: duplicate value for resource 'attr/chipSpacing' with config ''.
Message{kind=ERROR, text=error: duplicate value for resource 'attr/chipSpacing' with config ''., sources=[C:\Users\Guitorio\.gradle\caches\transforms-1\files-1.1\appcompat-v7-28.0.0.aar\2fb514f3e3159b1429d74f6160dbd78e\res\values\values.xml:1304:5-69], original message=, tool name=Optional.of(AAPT)}
This problem is not yet sorted out....

**Comment by simon-tse-hs** [comment]
@guitorioadar try using vdrsion 1.2.0, it should have resolved this issue.
