### ISSUE TITLE
Loading Indicator?

### ISSUE THREAD

**Issue by ericcarboni** [hootsuite/nachos#7]
Is there any way to add loading indicator functionality to this library?

**Comment by neil-power-hs** [comment]
Where would you like the loading indicator? Do you have a screenshot of where it is needing to load?

**Comment by ericcarboni** [comment]
I'm filling the suggestions from an API call, so I would like to give visual feedback that the call is being made. So currently, I am able to use `setLoadingIndicator()` on my AutoCompleteTextView and it takes in the resource id as a parameter. I have a standard ProgressBar widget aligned on the right side of the search view, which is what that points to.

**Comment by sherry-yuan-hs** [comment]
@ericcarboni We don't plan on adding a loading indicator feature since it's an uncommon use case. Using a ProgressBar is a good idea, and feel free to extend the library when using it for your own projects.
